-- CreateTable
CREATE TABLE "RASPBERRYPI" (
    "id" SERIAL NOT NULL,
    "piName" TEXT NOT NULL,
    "ip" TEXT NOT NULL,

    CONSTRAINT "RASPBERRYPI_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PLANT" (
    "id" SERIAL NOT NULL,
    "piID" INTEGER NOT NULL,

    CONSTRAINT "PLANT_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PLANTDATA" (
    "time" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "temperature" DOUBLE PRECISION NOT NULL,
    "light" DOUBLE PRECISION NOT NULL,
    "humidity" DOUBLE PRECISION NOT NULL,
    "gasConc" DOUBLE PRECISION NOT NULL,
    "plantId" INTEGER NOT NULL,

    CONSTRAINT "PLANTDATA_pkey" PRIMARY KEY ("time")
);

-- CreateIndex
CREATE UNIQUE INDEX "PLANT_id_key" ON "PLANT"("id");

-- AddForeignKey
ALTER TABLE "PLANT" ADD CONSTRAINT "PLANT_piID_fkey" FOREIGN KEY ("piID") REFERENCES "RASPBERRYPI"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PLANTDATA" ADD CONSTRAINT "PLANTDATA_plantId_fkey" FOREIGN KEY ("plantId") REFERENCES "PLANT"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
SELECT create_hypertable('"PLANTDATA"', 'time');